/**
 * @file resources/invoices.ts
 * @description Invoices resource for the Workbench SDK
 *
 * Provides methods for managing invoices in Workbench CRM.
 */

import type { WorkbenchClient } from '../client.js';
import type {
  Invoice,
  CreateInvoiceOptions,
  UpdateInvoiceOptions,
  ListInvoicesOptions,
  ApiResponse,
  ListResponse,
} from '../types/index.js';

/**
 * Invoices resource
 *
 * @example
 * ```typescript
 * const workbench = new WorkbenchClient({ apiKey: 'wbk_live_xxx' });
 *
 * // Create an invoice
 * const { data: invoice } = await workbench.invoices.create({
 *   client_id: 'client-uuid',
 *   items: [
 *     { description: 'Consulting', quantity: 2, unit_price: 150 },
 *     { description: 'Materials', quantity: 1, unit_price: 50 }
 *   ],
 *   tax_rate: 8.5,
 *   notes: 'Thank you for your business!'
 * });
 *
 * // Send the invoice
 * await workbench.invoices.send(invoice.id);
 * ```
 */
export class InvoicesResource {
  private readonly client: WorkbenchClient;

  constructor(client: WorkbenchClient) {
    this.client = client;
  }

  /**
   * List all invoices
   *
   * Returns a paginated list of invoices for the authenticated business.
   *
   * @param options - List options (pagination, filtering, sorting)
   * @returns Paginated list of invoices
   *
   * @example
   * ```typescript
   * // List unpaid invoices
   * const { data, pagination } = await workbench.invoices.list({
   *   status: 'sent',
   *   per_page: 50
   * });
   * ```
   */
  async list(options: ListInvoicesOptions = {}): Promise<ListResponse<Invoice>> {
    return this.client.get<ListResponse<Invoice>>('/v1/invoices', {
      page: options.page,
      per_page: options.per_page,
      search: options.search,
      sort: options.sort,
      order: options.order,
      status: options.status,
      client_id: options.client_id,
    });
  }

  /**
   * Get an invoice by ID
   *
   * @param id - Invoice UUID
   * @returns Invoice details with line items
   *
   * @example
   * ```typescript
   * const { data: invoice } = await workbench.invoices.get('invoice-uuid');
   * console.log(`Invoice ${invoice.invoice_number}: $${invoice.total}`);
   * ```
   */
  async get(id: string): Promise<ApiResponse<Invoice>> {
    return this.client.get<ApiResponse<Invoice>>(`/v1/invoices/${id}`);
  }

  /**
   * Create a new invoice
   *
   * Creates an invoice with line items. The invoice number is
   * automatically generated by Workbench.
   *
   * @param data - Invoice data including line items
   * @returns Created invoice
   *
   * @example
   * ```typescript
   * const { data: invoice } = await workbench.invoices.create({
   *   client_id: 'client-uuid',
   *   due_date: '2024-02-15',
   *   items: [
   *     { description: 'Web Development', quantity: 10, unit_price: 100 }
   *   ],
   *   tax_rate: 8.5,
   *   notes: 'Payment due within 30 days'
   * });
   * ```
   */
  async create(data: CreateInvoiceOptions): Promise<ApiResponse<Invoice>> {
    return this.client.post<ApiResponse<Invoice>>('/v1/invoices', data);
  }

  /**
   * Update an invoice
   *
   * If items are provided, they will replace all existing line items.
   *
   * @param id - Invoice UUID
   * @param data - Fields to update
   * @returns Updated invoice
   *
   * @example
   * ```typescript
   * const { data: invoice } = await workbench.invoices.update('invoice-uuid', {
   *   status: 'paid',
   *   notes: 'Paid via bank transfer on 2024-01-15'
   * });
   * ```
   */
  async update(id: string, data: UpdateInvoiceOptions): Promise<ApiResponse<Invoice>> {
    return this.client.put<ApiResponse<Invoice>>(`/v1/invoices/${id}`, data);
  }

  /**
   * Delete an invoice
   *
   * Permanently deletes an invoice and all associated line items.
   * This action cannot be undone.
   *
   * @param id - Invoice UUID
   *
   * @example
   * ```typescript
   * await workbench.invoices.delete('invoice-uuid');
   * ```
   */
  async delete(id: string): Promise<void> {
    await this.client.delete<void>(`/v1/invoices/${id}`);
  }

  /**
   * Send an invoice via email
   *
   * Sends the invoice to the client's email address. The invoice
   * status will be updated to 'sent' if currently 'draft'.
   *
   * @param id - Invoice UUID
   * @returns Success response
   *
   * @example
   * ```typescript
   * await workbench.invoices.send('invoice-uuid');
   * console.log('Invoice sent successfully');
   * ```
   */
  async send(id: string): Promise<ApiResponse<{ message: string; invoice_id: string }>> {
    return this.client.post<ApiResponse<{ message: string; invoice_id: string }>>(`/v1/invoices/${id}/send`);
  }
}
