/**
 * @file resources/quotes.ts
 * @description Quotes resource for the Workbench SDK
 *
 * Provides methods for managing quotes/estimates in Workbench CRM.
 */

import type { WorkbenchClient } from '../client.js';
import type {
  Quote,
  CreateQuoteOptions,
  UpdateQuoteOptions,
  ListQuotesOptions,
  ApiResponse,
  ListResponse,
} from '../types/index.js';

/**
 * Quotes resource
 *
 * @example
 * ```typescript
 * const workbench = new WorkbenchClient({ apiKey: 'wbk_live_xxx' });
 *
 * // Create a quote
 * const { data: quote } = await workbench.quotes.create({
 *   client_id: 'client-uuid',
 *   valid_until: '2024-02-28',
 *   items: [
 *     { description: 'Kitchen Renovation', quantity: 1, unit_price: 5000 },
 *     { description: 'Materials', quantity: 1, unit_price: 2500 }
 *   ]
 * });
 *
 * // Send the quote
 * await workbench.quotes.send(quote.id);
 * ```
 */
export class QuotesResource {
  private readonly client: WorkbenchClient;

  constructor(client: WorkbenchClient) {
    this.client = client;
  }

  /**
   * List all quotes
   *
   * Returns a paginated list of quotes for the authenticated business.
   *
   * @param options - List options (pagination, filtering, sorting)
   * @returns Paginated list of quotes
   *
   * @example
   * ```typescript
   * // List pending quotes
   * const { data, pagination } = await workbench.quotes.list({
   *   status: 'sent',
   *   per_page: 20
   * });
   * ```
   */
  async list(options: ListQuotesOptions = {}): Promise<ListResponse<Quote>> {
    return this.client.get<ListResponse<Quote>>('/v1/quotes', {
      page: options.page,
      per_page: options.per_page,
      search: options.search,
      sort: options.sort,
      order: options.order,
      status: options.status,
      client_id: options.client_id,
    });
  }

  /**
   * Get a quote by ID
   *
   * @param id - Quote UUID
   * @returns Quote details with line items
   *
   * @example
   * ```typescript
   * const { data: quote } = await workbench.quotes.get('quote-uuid');
   * console.log(`Quote ${quote.quote_number}: $${quote.total}`);
   * ```
   */
  async get(id: string): Promise<ApiResponse<Quote>> {
    return this.client.get<ApiResponse<Quote>>(`/v1/quotes/${id}`);
  }

  /**
   * Create a new quote
   *
   * Creates a quote with line items. The quote number is
   * automatically generated by Workbench.
   *
   * @param data - Quote data including line items
   * @returns Created quote
   *
   * @example
   * ```typescript
   * const { data: quote } = await workbench.quotes.create({
   *   client_id: 'client-uuid',
   *   valid_until: '2024-03-01',
   *   items: [
   *     { description: 'Plumbing Service', quantity: 4, unit_price: 75 }
   *   ],
   *   notes: 'Quote valid for 30 days',
   *   terms: 'Payment due upon completion'
   * });
   * ```
   */
  async create(data: CreateQuoteOptions): Promise<ApiResponse<Quote>> {
    return this.client.post<ApiResponse<Quote>>('/v1/quotes', data as Record<string, unknown>);
  }

  /**
   * Update a quote
   *
   * If items are provided, they will replace all existing line items.
   *
   * @param id - Quote UUID
   * @param data - Fields to update
   * @returns Updated quote
   *
   * @example
   * ```typescript
   * const { data: quote } = await workbench.quotes.update('quote-uuid', {
   *   status: 'approved',
   *   notes: 'Client approved via email on 2024-01-15'
   * });
   * ```
   */
  async update(id: string, data: UpdateQuoteOptions): Promise<ApiResponse<Quote>> {
    return this.client.put<ApiResponse<Quote>>(`/v1/quotes/${id}`, data as Record<string, unknown>);
  }

  /**
   * Delete a quote
   *
   * Permanently deletes a quote and all associated line items.
   * This action cannot be undone.
   *
   * @param id - Quote UUID
   *
   * @example
   * ```typescript
   * await workbench.quotes.delete('quote-uuid');
   * ```
   */
  async delete(id: string): Promise<void> {
    await this.client.delete<void>(`/v1/quotes/${id}`);
  }

  /**
   * Send a quote via email
   *
   * Sends the quote to the client's email address. The quote
   * status will be updated to 'sent' if currently 'draft'.
   *
   * @param id - Quote UUID
   * @returns Success response
   *
   * @example
   * ```typescript
   * await workbench.quotes.send('quote-uuid');
   * console.log('Quote sent successfully');
   * ```
   */
  async send(id: string): Promise<ApiResponse<{ message: string; quote_id: string }>> {
    return this.client.post<ApiResponse<{ message: string; quote_id: string }>>(`/v1/quotes/${id}/send`);
  }
}
